name: Deploy to Neocities
on:
  push:
    branches:
      - system64.neocities.org
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Yooo new site update, I gotchu."
      - name: Use Node.JS :)
        uses: actions/setup-node@v1
          with: 
            node-version: 12
      - name: Install dependents and build.
        run: | 
          npm i
          npm run build
      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1.1.4
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          dist_dir: public
       - run: echo "Done!"
